/**
 * TypeScript Types for TrueTaste Order Management
 * 
 * These types define the data structures used when placing orders
 * through AWS API Gateway to Lambda and DynamoDB.
 */

/**
 * Represents a single item in an order
 */
export interface OrderItem {
    /** Product ID from your product catalog */
    productId: string;

    /** Product name for display purposes */
    productName: string;

    /** Quantity of this product ordered */
    quantity: number;

    /** Unit price of the product */
    price: number;
}

/**
 * Complete order payload sent to AWS API Gateway
 */
export interface OrderPayload {
    /** Firebase user ID - identifies who placed the order */
    userId: string;

    /** Array of items in the order */
    items: OrderItem[];

    /** Total order amount (including tax and shipping) */
    total: number;

    /** Optional subtotal before tax and shipping */
    subtotal?: number;

    /** Optional shipping cost */
    shipping?: number;

    /** Optional tax amount */
    tax?: number;

    /** Shipping address information */
    shippingAddress?: {
        fullName: string;
        email: string;
        phone: string;
        address: string;
        city: string;
        postalCode: string;
        country?: string;
    };

    /** Payment method used (e.g., 'credit_card', 'cash_on_delivery') */
    paymentMethod?: string;

    /** Any additional notes or special instructions */
    notes?: string;

    /** Timestamp when order was placed (ISO string) */
    timestamp?: string;
}

/**
 * Response from AWS Lambda after successfully creating an order
 */
export interface OrderResponse {
    /** Success status */
    success: boolean;

    /** Order ID generated by DynamoDB */
    orderId: string;

    /** User-friendly order number */
    orderNumber?: string;

    /** Complete order details */
    order?: {
        orderId: string;
        userId: string;
        items: OrderItem[];
        total: number;
        status: string;
        createdAt: string;
        orderNumber?: string;
    };

    /** Success message */
    message?: string;
}

/**
 * Error response from AWS API
 */
export interface ApiError {
    /** Error status */
    success: false;

    /** Error message */
    error: string;

    /** Additional error details */
    details?: string;

    /** HTTP status code */
    statusCode?: number;
}

/**
 * Type guard to check if a response is an error
 */
export function isApiError(response: OrderResponse | ApiError): response is ApiError {
    return 'error' in response && response.success === false;
}
