// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ombtewotvripzfpyvyem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYnRld290dnJpcHpmcHl2eWVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzMyMjIsImV4cCI6MjA3MjU0OTIyMn0.Cg1LBFI3-0W_4g46P8b1l5Mhx-Y7b4zaG6Eywy-wAlY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});